/**
 * Canonical Indian city names for profiles (onboarding + preferences).
 * Keep in sync with `frontend/src/shared/data/pitchside-cities.ts`.
 */
export const PITCHSIDE_CITY_NAMES = [
  'Agartala',
  'Agra',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Akola',
  'Alappuzha',
  'Aligarh',
  'Alwar',
  'Ambala',
  'Amravati',
  'Amritsar',
  'Anand',
  'Asansol',
  'Aurangabad',
  'Bengaluru',
  'Bareilly',
  'Bathinda',
  'Belagavi',
  'Berhampur',
  'Bhagalpur',
  'Bharatpur',
  'Bhavnagar',
  'Bhilai',
  'Bhopal',
  'Bhubaneswar',
  'Bikaner',
  'Bilaspur',
  'Bokaro Steel City',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Cuttack',
  'Darjeeling',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Dharamshala',
  'Dibrugarh',
  'Dimapur',
  'Durgapur',
  'Ernakulam',
  'Faridabad',
  'Gandhinagar',
  'Gangtok',
  'Ghaziabad',
  'Goa',
  'Gorakhpur',
  'Greater Noida',
  'Guntur',
  'Guwahati',
  'Gwalior',
  'Hisar',
  'Howrah',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Itanagar',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jalgaon',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jhansi',
  'Jodhpur',
  'Jorhat',
  'Kalyan',
  'Kanchipuram',
  'Kannur',
  'Kanpur',
  'Karnal',
  'Kharagpur',
  'Kochi',
  'Kohima',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Kota',
  'Kozhikode',
  'Kurnool',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangaluru',
  'Meerut',
  'Moradabad',
  'Mumbai',
  'Muzaffarnagar',
  'Muzaffarpur',
  'Mysuru',
  'Nagercoil',
  'Nagpur',
  'Nanded',
  'Nashik',
  'Navi Mumbai',
  'Nellore',
  'Noida',
  'Panaji',
  'Panipat',
  'Parbhani',
  'Patiala',
  'Patna',
  'Puducherry',
  'Pune',
  'Raipur',
  'Rajahmundry',
  'Rajkot',
  'Ranchi',
  'Rohtak',
  'Rourkela',
  'Salem',
  'Shillong',
  'Shimla',
  'Shimoga',
  'Silchar',
  'Siliguri',
  'Solapur',
  'Sonipat',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupati',
  'Tiruppur',
  'Udaipur',
  'Ujjain',
  'Vadodara',
  'Varanasi',
  'Vasai-Virar',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
] as const;

export type PitchsideCityName = (typeof PITCHSIDE_CITY_NAMES)[number];

export const PITCHSIDE_CITY_SET: ReadonlySet<string> = new Set(PITCHSIDE_CITY_NAMES);

/** For `class-validator` `@IsIn` — tuple cast. */
export const PITCHSIDE_CITY_NAMES_FOR_ISIN = [...PITCHSIDE_CITY_NAMES] as unknown as string[];

export function isPitchsideCityName(value: string): boolean {
  return PITCHSIDE_CITY_SET.has(value.trim());
}
